### PR TITLE
Preview of ocamlformat.0.16.0

### PR DESCRIPTION
**Pull request by gpetiot**
Hi, this pull-request is a preview of the soon to be released ocamlformat.0.16.0. The main change in the diff is that `indicate-multiline-delimiters` option has now be switched to `no` on the conventional profile to improve consistency and minimize the diffs in the future.
Let me now if you notice any regressions.

### CODE REVIEW

**Review by smorimoto — APPROVED** [review]

**Comment by smorimoto** [comment]
It has already been released, so I think we can merge this after update this line.
https://github.com/ocamllabs/vscode-ocaml-platform/blob/2443f183e1892caee66afab79044bd0f4903b27d/esy.json#L13

**Comment by mnxn** [comment]
I think we have some dependency problems if we try to upgrade to 0.16.0 in CI. If I try to upgrade locally:

```
$ opam install ocamlformat.0.16.0
The following actions will be performed:
  ⊘ remove    core_kernel             v0.14.1            [uses ppx_jane]
  ⊘ remove    promise_jsoo            0.2.0              [uses gen_js_api]
  ⊘ remove    jsonoo                  0.2.0              [uses gen_js_api]
  ⊘ remove    base_bigstring          v0.14.0            [uses ppx_jane]
  ⊘ remove    gen_js_api              1.0.6              [conflicts with ppxlib]
  ⊘ remove    ppx_jane                v0.14.0            [conflicts with ppxlib]
  ↗ upgrade   ocaml-migrate-parsetree 1.8.0 to 2.1.0     [required by ppxlib]
  ⊘ remove    ppx_bin_prot            v0.14.0            [conflicts with ppxlib]
  ⊘ remove    bin_prot                v0.14.0            [conflicts with ppx_fields_conv]
  ⊘ remove    ppx_custom_printf       v0.14.0            [conflicts with ppxlib]
  ↗ upgrade   ppxlib                  0.15.0 to 0.20.0   [required by ocamlformat]
  ↗ upgrade   ppx_sexp_conv           v0.14.1 to v0.14.2 [uses ppxlib]
  ↗ upgrade   ppx_optcomp             v0.14.0 to v0.14.1 [uses ppxlib]
  ↗ upgrade   ppx_fields_conv         v0.14.1 to v0.14.2 [uses ppxlib]
  ↗ upgrade   ocamlformat             0.15.0 to 0.16.0
```

We depend on `core_kernel`, `promise_jsoo`, `jsonoo`, and `gen_js_api` directly.

**Comment by rgrinberg** [comment]
Let's cc @emillon. Usually such issues are quickly addressed with a point release.

**Comment by emillon** [comment]
I think that there's an upcoming release of the JS ppx (including `ppx_jane`) which should fix that.

**Comment by emillon** [comment]
If you want a more incremental upgrade, you can do it in 2 steps:
- first upgrade to ocamlformat 0.15.1 and the upcoming set of JS packages compatible with OMP2 (that will happen with no formatting changes)
- then upgrade to ocamlformat 0.16.0

**Comment by tmattio** [comment]
Closing this, we'll move to 0.17.0 directly once we update the formatting

**Pull request closed without merging**
