### PR TITLE
Update build-platform.yml

### PR DESCRIPTION
**Pull request by imbsky**

### CODE REVIEW

**Comment by rgrinberg** [comment]
Looks good. I think we need an issue to remove this duplication of information. It will be quite easy to forget to change this otherwise

**Comment by imbsky** [comment]
Agree.

**Comment by imbsky** [comment]
I made an issue, so I would like to merge it once. As for the test, it doesn't seem to work properly, so I think it needs to be fixed. We can fix the test using JavaScript, or rewrite test using MDX instead.

**Comment by imbsky** [comment]
Well, I'm not familiar with MDX, so I don't know if we can test this with MDX.

**Pull request merged**
