### PR TITLE
Update ovsx to latest

### PR DESCRIPTION
**Pull request by smorimoto**

### CODE REVIEW

**Review by mnxn — APPROVED** [review]

**Comment by mnxn** [comment]
If I try to publish with `ovsx@0.1.0-next.4742dff` manually I get a different error now:

```
/Users/max/Projects/vscode-ocaml-platform/node_modules/commander/index.js:472
      throw new Error(`option '${option.name()}' clashes with existing property '${option.attributeName()}' on Command
      ^

Error: option 'version' clashes with existing property 'version' on Command
- call storeOptionsAsProperties(false) to store option values safely,
- or call storeOptionsAsProperties(true) to suppress this check,
- or change option name

Read more on https://git.io/JJc0W
    at Command._checkForOptionNameClash (/Users/max/Projects/vscode-ocaml-platform/node_modules/commander/index.js:472:13)
    at Command._optionEx (/Users/max/Projects/vscode-ocaml-platform/node_modules/commander/index.js:499:10)
    at Command.option (/Users/max/Projects/vscode-ocaml-platform/node_modules/commander/index.js:622:17)
    at module.exports (/Users/max/Projects/vscode-ocaml-platform/node_modules/ovsx/lib/main.js:58:10)
    at Object.<anonymous> (/Users/max/Projects/vscode-ocaml-platform/node_modules/ovsx/lib/ovsx:2:18)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
error Command failed with exit code 1.
```

**Comment by mnxn** [comment]
Updating to `ovsx@0.1.0-next.97d460c` worked with no errors however.

**Comment by smorimoto** [comment]
@spoenemann Any idea?

**Comment by spoenemann** [comment]
Yes there was a breaking change in [commander](https://www.npmjs.com/package/commander) that affects the `--version` option that we used for the `get` command. It should be fixed with `latest` as mentioned by @mnxn.

**Comment by mnxn** [comment]
Thanks @spoenemann! We'll update to that version.

@smorimoto: shouldn't dependabot be creating PRs to bump ovsx? The last PR was [on Dec 8th](https://github.com/ocamllabs/vscode-ocaml-platform/pull/474). 
Or does the hash at the end interfere with its updating algorithm? I'm not experienced enough with dependabot to know myself.

**Review by mnxn — APPROVED** [review]

**Comment by smorimoto** [comment]
I just switched to `0.1.0-next.97d460c`. Will this probably fix it?

**Comment by smorimoto** [comment]
```
~/src/github.com/ocamllabs/vscode-ocaml-platform
λ yarn ovsx --version
yarn run v1.22.10
warning ocaml-platform@1.6.0: The engine "vscode" appears to be invalid.
$ /home/smorimoto/src/github.com/ocamllabs/vscode-ocaml-platform/node_modules/.bin/ovsx --version
0.1.0-next.97d460c
Done in 0.24s.
```

**Comment by mnxn** [comment]
> I just switched to `0.1.0-next.97d460c`. Will this probably fix it?

Yes, I didn't have any errors when I published with `97d460c`.

**Comment by smorimoto** [comment]
Okay, cool!

**Pull request merged**
