### PR TITLE
Use stable lsp package in test fixture for esy

### PR DESCRIPTION
**Pull request by smorimoto**

### CODE REVIEW

**Comment by rgrinberg** [comment]
Why are we switching from yarn to npm? Somebody made a PR to switch to npm recently so this is going contrary to that.

**Comment by smorimoto** [comment]
It was done in https://github.com/ocamllabs/vscode-ocaml-platform/pull/726 by @tmattio. But npm isn't really that good, and it's rather unstable. In actual practice, yarn is much better. Also, even if you prefer npm, you can still install consistent packages using npm because the latest release already supports parsing of the yarn lock file. So switching to npm wasn't exactly an improvement.

**Comment by smorimoto** [comment]
This will not only make use of the stable version of lsp, but also restore the esy cache. Now that GitHub Actions has increased the maximum cache limit, everything is fine.

**Comment by smorimoto** [comment]
I think it will be simpler to use workspaces in the future, but that's not the scope of this PR, so I would like to do it in a different PR.
https://classic.yarnpkg.com/lang/en/docs/workspaces

**Comment by ulugbekna** [comment]
In current master, we use both yarn and npm in Makefile. I think it's nice that we're settling with one of the them

**Comment by smorimoto** [comment]
Now this PR is ready to merge!

**Comment by tatchi** [comment]
Shouldn't we delete the `package-lock.json` file now that we've switched over to `yarn`?

**Comment by smorimoto** [comment]
Oops... Indeed yes.

**Pull request merged**
