### PR TITLE
OCaml earlybird debugger integration

### PR DESCRIPTION
**Pull request by hackwaly**

### CODE REVIEW

**Comment by hackwaly** [comment]
Current status:
image

**Comment by ulugbekna** [comment]
Hi @hackwaly, how's this PR going? Any help needed? 

Regarding the code lenses for running dune executables, do you think it's worth a separate PR? 
1) PRs stay smaller and more reviewable
2) We merge new functionality faster
3) It doesn't seem too tightly coupled to debugger integration

**Comment by hackwaly** [comment]
> Hi @hackwaly, how's this PR going? Any help needed?
> 
> Regarding the code lenses for running dune executables, do you think it's worth a separate PR?
> 
> 1. PRs stay smaller and more reviewable
> 2. We merge new functionality faster
> 3. It doesn't seem too tightly coupled to debugger integration

Yes. A separated PR is better. But it depends on the debugger function. I shall separate it when debugger function ready.

BTW. The progress sometimes stuck while I'm busy on other things.

**Comment by hackwaly** [comment]
Status updated.


https://user-images.githubusercontent.com/540298/127650668-ef91fae6-75db-45c6-8b58-b4c751faa0f6.mp4

**Comment by ulugbekna** [comment]
Hi @hackwaly,

Thanks for getting this PR to a ready state. 

1. Do you mind writing a short manual on how to use this feature? The more detailed it is, the better. For example, I was trying the feature out, and it took me some time to understand that I need to manually put `(modes byte)` for the debug code lens to appear. The manual can be written in the README. We also need a note about the feature in the changelog I think.
2. One can't run the debugger with dune libraries used for testings, eg `fiber-unix/test/dune`. I assume that's a limitation of one of the tools earlybird relies on: ocamldebug, dune, etc. So what is it?

**Comment by ulugbekna** [comment]
Also, how okay is it that I'm getting segfaults? 👀 

```
$ cd /Users/ulugbekna/code/channels/_build/default ; /usr/bin/env CAML_DEBUG_SOCKET=127.0.0.1:59985 /Users/ulugbekna/code/channels/_build/default/channels.bc 
[1]    40607 segmentation fault  /usr/bin/env CAML_DEBUG_SOCKET=127.0.0.1:59985 
```

**Comment by hackwaly** [comment]
This might be an issue of ocamlearlybird. Have you tried a simpler one?



---Original---
From: "Ulugbek ***@***.***&gt;
Date: Sun, Aug 8, 2021 21:23 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ocamllabs/vscode-ocaml-platform] OCaml earlybird debugger integration (#650)




 
Also, how okay is it that I'm getting segfaults? 👀
 $ cd /Users/ulugbekna/code/channels/_build/default ; /usr/bin/env CAML_DEBUG_SOCKET=127.0.0.1:59985 /Users/ulugbekna/code/channels/_build/default/channels.bc  [1]    40607 segmentation fault  /usr/bin/env CAML_DEBUG_SOCKET=127.0.0.1:59985   
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hackwaly** [comment]
Thank you for your reviewing. I'll add manual for it. Debug testing is a good suggestion. I'll trying to implement it in this PR.



---Original---
From: "Ulugbek ***@***.***&gt;
Date: Sun, Aug 8, 2021 20:13 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ocamllabs/vscode-ocaml-platform] OCaml earlybird debugger integration (#650)




 
Hi @hackwaly,
 
Thanks for getting this PR to a ready state.
  
Do you mind writing a short manual on how to use this feature? The more detailed it is, the better. For example, I was trying the feature out, and it took me some time to understand that I need to manually put (modes byte) for the debug code lens to appear. The manual can be written in the README. We also need a note about the feature in the changelog I think. 

One can't run the debugger with dune libraries used for testings, eg fiber-unix/test/dune. I assume that's a limitation of one of the tools earlybird relies on: ocamldebug, dune, etc. So what is it? 
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by rgrinberg** [comment]
@hackwaly feel free to re-open once you update the PR.

**Pull request closed without merging**
