### PR TITLE
Dune syntax highlighting fix

### PR DESCRIPTION
**Pull request by SaySayo**
Fixed the dune syntax by rewriting the dune.json in a similar fashion to the dune-project.json and dune-workspace.json syntaxes (#106). @mnxn please review

### CODE REVIEW

**Comment by mnxn** [comment]
>  either constants, variables, keywords, or strings.

If it's not one of those, then don't include the `contentName` field, it's optional.

**Comment by rgrinberg** [comment]
@SaySayo do you plan to work on this PR?

**Comment by SaySayo** [comment]
Yes I do. I made the changes @mnxn requested and I'm waiting on a review.

**Comment by mnxn** [comment]
Sorry for not looking at this earlier.

I tested this syntax with some example `dune` files from [the dune repo](https://github.com/ocaml/dune) and there are still many unrecognized fields:
<details>
  <summary>Examples</summary>

image

image

image

image

image

</details>

I think there is still a lot of work left until this syntax is complete. The core issue is that there are too many unrelated fields in certain rules: [like this line for example](https://github.com/ocamllabs/vscode-ocaml-platform/blob/3b52f3143d89caff25e970d5fb2d6b4c9ba1201b/syntaxes/dune.json#L137). Some of the fields can have extra options or specific input, so it doesn't make sense to combine them all.

What could make this easier to work on is an example `dune` file that covers most of the `dune` syntax. That way you would just need to scroll through that file to see what is being highlighted correctly or not. Unfortunately, I haven't found anything like that so far.

I don't want to merge this PR until the syntax is complete. You are free to keep working on this if you want, but I can't guarantee to keep up with code reviews. I've had much less time for reviews recently and this is a very big PR.

**Comment by SaySayo** [comment]
I'll keep working on this PR till it fixes all the issues you mentioned, might take me a couple weeks as I have less time to work on it. I'll ping you when I think its fully ready for a review so as to reduce the amount of times you have to run a review on this PR. In the meantime I'll convert this PR to a draft since it's not ready to be merged while I continue to work on it.

**Comment by mnxn** [comment]
Sounds good. Thanks.

**Comment by tmattio** [comment]
@mnxn We're currently reviewing the PR with @SaySayo and are not sure how to address your comment about the unrecognized fields.

You previously mentioned:
> Overuse of `variable.other.declaration.dune`. I only used this scope name when something is being declared. In this example, I would only expect public_name and name to have the variable.other.declaration.dune highlighting.

And advised that some fields should not be highlighted.

In your last comment, though, you're mentioning that 
> I tested this syntax with some example dune files from the dune repo and there are still many unrecognized fields:

IIUC, these were previously highlighted, but @SaySayo removed it after your comment. What would you recommend we do? Should we create a new scope for these? Do you have any guidelines you're following to decide what is a `variable.other.declaration.dune` and what is not?

Personally, I think that's fine if all the fields are highlighted, but we'll follow your recommendation here.

**Comment by mnxn** [comment]
Sorry, I will try to use more specific language.

From now on I will refer to field _names_ and field _values_. In the snippet `(a b)`, `a` is the field _name_ and `b` is the field _value_.

What I previously mentioned was that only the field _values_ for `public_name` and `name` should use `variable.other.declaration.dune`. What I forgot to say back that then is that field _values_ for the plurals, `public_names` and `names`, should also be `variable.other.declaration.dune`.

So __only__ field _values_ for `public_name`, `public_names`, `name`, and `names` should use `variable.other.declaration.dune`.

My most recent screenshots were mostly to point out the missing field _name_ highlighting. We should aim to highlight all valid field _names_ in the appropriate contexts.

I'll go over the specific changes in those screenshots I would expect. This time I will use the built-in `Dark+` theme.

1. 
  i.  `names` should be highlighted with `keyword.language.dune`
  ii. `foo` should be highlighted with `variable.other.declaration.dune`
  iii. `libraries` should be highlighted with `keyword.language.dune`

2. 
  i. `gh637` should be highlighted with `variable.other.declaration.dune`
  ii. `package` should be highlighted with `keyword.language.dune`
  iii. `libraries` should be highlighted with `keyword.language.dune`
  iv. `deps` should be highlighted with `keyword.language.dune`
 
3. 
  i. `language` should be highlighted with `keyword.language.dune`
  ii. `names` should be highlighted with `keyword.language.dune`
 
4. 
  i. `with-stdout-to` should be highlighted with `entity.name.function.action.dune`
  ii. `run` should be highlighted with `entity.name.function.action.dune`

5. 
  i. `backend` should be highlighted with `keyword.language.dune`
  ii. `executable` should be highlighted with `keyword.language.dune`
  iii. `flags` should be highlighted with `keyword.language.dune`

**Comment by SaySayo** [comment]
Hello @mnxn I updated the dune syntax to address all the things you mentioned. Works well locally. Please review when you can and let me know if there's any required changes. Thank you!

**Comment by tmattio** [comment]
@mnxn Thanks a lot for the very detailed and comprehensive answer, it's very helpful 🙂 

@SaySayo I'd like to test the PR with some more dune files to see if we can spot other issues before asking @mnxn to review again if that's ok with you. I'll ping here if everything looks after testing.

**Comment by SaySayo** [comment]
Yes that's fine @tmattio. Thank you for your time!

**Comment by tmattio** [comment]
@mnxn I completed an initial review of the PR and I believe it is ready for you to review as well.

I noticed some issues that should be addressed:

- We are forgetting to include `#general` in some places, which breaks the syntax highlighting for comments in some stanzas, among other things
- the env stanza fields are not highlighted
- include_subdirs values are not highlighted
- The variable highlighting is too general, for instance, the extension `.exe` is highlighted in `%{exe:my_test_program.exe}`.

However, fixing these shouldn't require massive changes, so it's not conflicting with additional reviews.

**Comment by mnxn** [comment]
> The variable highlighting is too general

@tmattio: 
The variable highlighting is actually the same across syntaxes for `dune`, `dune-project`, and `dune-workspace`. I think it should be fixed in a later change so this PR stays isolated.

**Comment by tmattio** [comment]
This is a huge undertaking, thank you so much for all your work on this @SaySayo. Congratulations on getting the PR merged 🎉 

Thanks a lot for all your time, patience, and support to get this ready to merge @mnxn. Truly appreciate it ❤️

**Comment by SaySayo** [comment]
I'm so excited to see the changes finally merged! Glad I could make a difference. Thank you so much for your extremely patient reviews and solving through all the blockers with me @tmattio @mnxn @gs0510. I really  appreciate it 🙂🙏

**Pull request merged**
