### PR TITLE
Add more patterns to `opam-metadata.source`

### PR DESCRIPTION
**Pull request by smorimoto**
https://dune.readthedocs.io/en/stable/dune-files.html#stanza-source

### CODE REVIEW

**Comment by smorimoto** [comment]
@mnxn We can also manage it as a single "hosting services" pattern, but I wasn't sure what the policy was.

**Comment by mnxn** [comment]
Since the structure of the repo name is the same for the 4 hosting services, I think it would be better to combine the 4 rules into one pattern.

**Comment by smorimoto** [comment]
Agreed 👍

**Comment by smorimoto** [comment]
OK, I updated.

**Review by mnxn — APPROVED** [review]

**Pull request merged**
