### PR TITLE
update latest ocaml-lsp version (for ocaml 4.13) to 1.9.1

### PR DESCRIPTION
**Pull request by ulugbekna**

### CODE REVIEW

**Comment by tmattio** [comment]
Doesn't 1.9.1 support formatting of dune files from LSP? Maybe we should also remove the "manual" formatting we do at the moment as part of this PR?

**Comment by ulugbekna** [comment]
I don’t remember. I’ll update  the PR after checking if necessary

**Comment by rgrinberg** [comment]
It's not supported because it relies on dune rpc which isn't released yet.

**Comment by ulugbekna** [comment]
> It's not supported because it relies on dune rpc which isn't released yet.

uh, indeed, merging then

**Pull request merged**
