### PR TITLE
Add workflow step to publish the extension to Open VSX

### LINKED ISSUE #438: Publish to open-vsx in CI
open-vsx is used by editors like VSCodium instead of the VSCode extension marketplace.

The process is similar to using the `vsce` tool, but requires another token:
https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

### PR DESCRIPTION
**Pull request by smorimoto**
Closes #438

### CODE REVIEW

**Comment by smorimoto** [comment]
Note that we need to add a secret named OPEN_VSX_TOKEN to this repository.

**Review by mnxn — APPROVED** [review]

**Comment by rgrinberg** [comment]
> Note that we need to add a secret named OPEN_VSX_TOKEN to this repository.

Where do I get this secret from?

**Comment by mnxn** [comment]
> Where do I get this secret from?

You can get it from [open-vsx.org](https://open-vsx.org) - sign in with GitHub and create an access token in settings.

The process is also described here: https://github.com/eclipse/openvsx/wiki/Publishing-Extensions#1-create-an-access-token

**Comment by mnxn** [comment]
I edited the workflow so it reads the token from an environmental variables. I don't think it changes anything, but it is the recommended way in the documentation: https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets#example-using-bash

**Pull request merged**
