### PR TITLE
Improve OCaml Syntax Highlighting

### LINKED ISSUE #180: Syntax highlighting for new quoted extensions syntax
https://github.com/ocaml/ocaml/blob/4.11/Changes#L8

### PR DESCRIPTION
**Pull request by mnxn**
Closes #180 
OCaml Syntax Highlighting for Quoted Extensions: 
| Old | New |
| - | - |
| old | new | 

Also fixes a fatal flaw in #175 that prevented function declarations from being highlighted:

| Old | New |
| - | - |
| old | new |

### CODE REVIEW

**Comment by imbsky** [comment]
@mnxn This looks good. Are there any additional changes you would like to make in this PR?

**Comment by imbsky** [comment]
Oh, you probably need to update the changelog.

**Comment by mnxn** [comment]
No, this is it. I just had to fix some problems that were introduced in previous changes.

**Comment by rgrinberg** [comment]
Just to clarify the policy on the change log:

* It should include bug fixes only when the bug was introduced in a previously released version. If the bug was only present in master, there's no need to mention it.

* It should mention new features being introduced in this release.

**Comment by imbsky** [comment]
Oops, you're right.

**Pull request merged**
