### PR TITLE
Update esy.json

### PR DESCRIPTION
**Pull request by imbsky**

### CODE REVIEW

**Comment by imbsky** [comment]
I updated the configuration for OCamlFormat 0.14.0 in a recent PR, but it seems like we still can't use it without some annoying overrides. I think we should revert that PR. What do you think?

**Comment by prometheansacrifice** [comment]
The overrides look good. I noticed `ocamlformat` hasn't been updated here, is it because it was updated in the other PR mentioned? Either ways, this PR is good to be merged

**Comment by prometheansacrifice** [comment]
Feel free to post the issues faced in the other PR - I'd like to understand issues faced

**Comment by imbsky** [comment]
Updated.

**Pull request merged**
